### ISSUE TITLE
subconns in transient failure after submitting traces

### ISSUE THREAD

**Issue by Kyle-sandeman-mrdfood** [influxdata/jaeger-influxdb#10]
A bit of context:
I am running jaeger-collector, jaeger-query and influxDB on an AWS instance, with other instance(s) having jaeger-agent reporting to it. All of them are running in docker.  

Yesterday I made some changes to my instrumentation and now any spans submitted via the program cause the query to "crash".
On the Jaeger UI I get
```HTTP Error: plugin error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: error while dialing: dial unix /tmp/plugin123955954: connect: connection refused"```
The UI works with spans from a different program, but after trying to view the "buggy" ones, the UI will not work at all.

Logs from making a "buggy" request: https://gist.github.com/Kyle-sandeman-mrdfood/d24d0f26ee7b05d50235efaa341c0758

I _think_ the query engine eventually recovers, as it was broken last night but worked now (no restart)

Although I have mentioned my instrumentation being possibly buggy, I am creating this issue since it leaves potential for bad clients to bring down a jaeger system...

please let me know if there is any further information you need.

**Comment by Kyle-sandeman-mrdfood** [comment]
something of note is that I need to restart both the collector and the query containers to get a working setup again (excluding possible self-recovery).

**Comment by Kyle-sandeman-mrdfood** [comment]
seems it's due to lack of validation on operation name:
https://github.com/influxdata/jaeger-influxdb/blob/b6984b5c7bc59260643eca60e2706d5b9c2f556e/dbmodel/to_domain_v1.go#L275
I found a `set_operation_name('')` in my code :)

**Comment by jacobmarble** [comment]
The legacy branch is no longer under active development. Happy to take a pull request, though.
