### ISSUE TITLE
Tag "trace_id" and trace id is written to the same field 

### ISSUE THREAD

**Issue by AlexShuraits** [influxdata/jaeger-influxdb#15]
I am facing the issue when adding tag named trace_id the values appear in the same column with real trace id. The value I am passing inside trace_id tag is uuid v4. 
And the result of it that jaeger query returns:
TraceID cannot be longer than 32 hex characters.
Not sure which other fields used by the plugin can be mixed up with the tag.

**Comment by jacobmarble** [comment]
@AlexShuraits that is correct, the tag key `trace_id` is used by the plugin. I'll document this better in the rewrite.
