### ISSUE TITLE
Support for influx db v1/v2 after migrating to influxdb IOx ??

### ISSUE THREAD

**Issue by cikupin** [influxdata/jaeger-influxdb#20]
Hi @jacobmarble @gianarb 

I've been planning to use this library for my company. Until on March 8 2021, I see that that this plugin is rewritten 2 days ago to support influxdb IOx after being unmaintained for almost 1 year. The codes are different than before.

I have a few question:

1. Does it still support influxdb v1/v2 ? Because your [pull request](https://github.com/influxdata/jaeger-influxdb/commit/d769f2948ad3e10e41f6a951f86bad481b15d21d) said `hard switch to influxdb IOx` 

2. You said in the readme that

```
The plugin enables querying InfluxDB via the Jaeger UI. The plugin does not support writes via the Jaeger 
Collector. To write traces to InfluxDB/IOx, use OpenTelemetry.
```

Does it means that if I use this library for jaeger, I should write trace directly to Influxdb IOx instead of send traces to jaeger? So jaeger will be used only as a UI for visualizing traces?

Thank you.

**Comment by jacobmarble** [comment]
@cikupin my apologies. I have restored the former code state to [branch legacy](https://github.com/influxdata/jaeger-influxdb/tree/legacy). I have also restored the former images to quay.io, in their former locations.

**Comment by jacobmarble** [comment]
Also, yes, our new approach is to use OpenTelemetry to write traces (Jaeger agents or collectors can still be involved) and Jaeger to query traces.

**Comment by cikupin** [comment]
@jacobmarble does the main branch can be used for influxdb v1/v2 ?

**Comment by jacobmarble** [comment]
@cikupin No, it cannot.

It seems that my experiment got picked up for real production use. I did not anticipate that. Does the `legacy` branch satisfy your need? Happy to have a zoom chat some time.
