### ISSUE TITLE
Cannot run all-in-one with docker

### ISSUE THREAD

**Issue by mholleville** [influxdata/jaeger-influxdb#7]
Hi ! I tried to run the plugin in docker container but I have this following error :

`error attempting to connect to plugin rpc client: exec: \".jaeger-influxdb\": executable file not found in $PATH"`

I've build `jaeger-influxdb` . My Docker command 

`docker run   -e SPAN_STORAGE_TYPE=grpc-plugin   -e GRPC_STORAGE_PLUGIN_BINARY=.jaeger-influxdb   -e GRPC_STORAGE_PLUGIN_CONFIGURATION_FINE=./config-example-v1.yaml   jaegertracing/all-in-one:1.13`

Can you explain me ?

**Comment by rawkode** [comment]
You need to use the InfluxData image:

quay.io/influxdb/jaeger-all-in-one-influxdb

**Comment by mholleville** [comment]
Tried without success.

I'm trying you're docker compose and I have this following error :

`HTTP Error: plugin error: rpc error: code = Unknown desc = database not found: tracing`

Strange because database was created 

`Creating distributed-calculator_influxdb_1 ... done`

**Comment by rawkode** [comment]
That last last means the container was created. You'll still need to create a tracing database from the CLI.

This is step 3 in the instructions.

You can create the database with

```
docker-compose exec influxdb bash
influx
CREATE DATABASE tracing
```

**Comment by mholleville** [comment]
Ok thank u ! Last question, I have this 

`jaeger-influxdb: failed to write batch: error="{"error":"retention policy not found: tracing"}`


Does it come from the configuration of the plot in the app or did I forget a step?

**Comment by mholleville** [comment]
Thank you ! it turns ! But last question, the configuration of the plot must be adapted to work with the plugin? I have the default traces but not those of my app (which worked with ES Storage)
